### ISSUE TITLE
Collection not found in History Lab database

### ISSUE THREAD

**Issue by GrayAlex49** [dgozal/histlabapi#1]
For at least 2 databases, getting the error 'Collection not found in History Lab database'

- Presidential Daily Briefing - neither using the collection name from the docs 'pdb' or the name returned from list_collections()

- Records from the CIA Freedom of Information Act Reading Room

**Comment by dgozal** [comment]
Hi Alex,

Sorry it took me so long to get back to you! Let me take a look at this
when I get home from work later.

Best,
Derrick

**Comment by dgozal** [comment]
Hey Alex,

I took a closer look at the collections and it looks like the team just changed the names of these databases. So 'cia' should still refer to the records from the CIA Freedom of Information Act Reading Room (now renamed to CIA CREST) and the Presidential Daily Briefings should correspond to 'briefing' instead of 'pdb.'

Whatever comes out of list_collections() should be the most up-to-date version of things. I'm no longer working with the History Lab so I haven't updated the official documentation in a while.

Hope this helps!
